BE013, BE017
akademia-envelo-3/moovelo-back pull request #159
Opened 2023-01-19 09:00 UTC by Norshyee

Zaimplementowano klasy modelowe wraz z adnotacjami JPA

2023-01-19 20:18 UTC, mstebel requested changes
Rafale, czapki z głów!

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/actors/Visitor.java
> +import liquibase.pro.packaged.I;
niepotrzebny import liquibase

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/categories/Category.java
> +@AllArgsConstructor
Czy w przypadku encji z generowanym id, nie powinno być konstruktora przyjmującego wszystkie wymagane parametry oprócz id? Dotyczy większości klas modelowych, do dyskusji

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/categories/CategoryProposal.java
> +    private LocalDateTime date;
może dodać od razu adnotację do date? 
@DateTimeFormat(pattern = "yyyy-MM-dd")

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/events/EventInfo.java
> +    private LocalDateTime startDate;
może dodać od razu adnotację do startDate?
@DateTimeFormat(pattern = "yyyy-MM-dd")

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/events/EventInfo.java
> +    @OneToOne(mappedBy = "eventInfo")
Zastanawiam się, czy tu nie powinno być @ManyToOne -> wiele eventów może być w 1 lokalizacji, np. na Cybernetyki 9, więc może nie ma potrzeby za każdym razem tworzyć nowej lokalizacji, tylko wyszukać po id w bazie

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/events/EventInfo.java
> +    @OneToOne
Tutaj bym zmieniła adnotację. Jedna kategoria może być przypisana do wielu EventInfo, myślę, że @ManyToOne od strony Eventu

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/events/Event.java
> +    private List<Hashtag> hashtags;
@ManyToMany(cascade = CascadeType.ALL)

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/groups/Group.java
> +    private LocalDateTime creationDate;
@DateTimeFormat(pattern = "yyyy-MM-dd")

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/surveys/Answer.java
> +    private String answerValue;
nazwa pola w diagramie klas to 'value', nie 'answerValue'

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/surveys/EventSurvey.java
> +    @OneToMany(mappedBy = "eventSurvey")
kaskady, najpierw musimy zapisać odpowiedź, żeby zapisać ankietę

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/Comment.java
> +    @OneToMany(mappedBy = "comment")
CascadeType.All?

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/Comment.java
> +    private List<Hashtag> hashtags;
komentarze chyba ostatecznie nie mają listy hashtagów

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/Comment.java
> +    private LocalDateTime date;
@DateTimeFormat(pattern = "yyyy-MM-dd")

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/Hashtag.java
> +    private List<Comment> comments;
nie jestem pewna, czy klasa Hashtag powinna mieć listę komentarzy, ta funkcjonalność była dyskutowana z Kamilem. Do dyskusji z całym backendem

2023-01-19 20:18 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/entity/Location.java
> +    EventInfo eventInfo;
@OneToMany

2023-01-19 20:18 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/entity/actors/User.java
> +    private Role role;
@Enumerated(EnumType.STRING)

2023-01-19 20:18 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/entity/events/Event.java
> +public class Event {
brakuje pola List<BasicUser> usersWithAccess

2023-01-19 20:18 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/entity/events/InternalEvent.java
> +    private List<BasicUser> invited;
W klasie InternalEvent nie ma pola invited, jest za to w klasie Event ->  List<<BasicUser>> usersWithAccess

2023-01-19 20:18 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/entity/events/CyclicEvent.java
> +    }
czy ten konstruktor jest potrzebny? jeśli przyjmujemy grupę jako parametr konstruktora, to powinniśmy z automatu pobrać listę members z grupy i dodać ją do listy usersWithAccess w klasie Event.

2023-01-19 20:18 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/entity/surveys/EventSurvey.java
> +    private List<BasicUser> surveys;
nazwa zmiennej surveyees

2023-01-19 20:22 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/entity/surveys/Answer.java
> +    private String answerValue;
value się gryzie z H2, tak samo user i group

2023-01-19 20:28 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/entity/surveys/Answer.java
> +    private String answerValue;
ok, zmieniłam nazwę pola w diagramie klas na answerValue

2023-01-20 10:47 UTC, RyszardEnv commented on src/main/java/pl/envelo/moovelo/entity/Comment.java
> +    @OneToMany(mappedBy = "comment")
Warto dorzucić

2023-01-20 10:52 UTC, RyszardEnv commented on src/main/java/pl/envelo/moovelo/entity/Comment.java
> +    private List<Hashtag> hashtags;
Tak, Hashtag jako Encja funkcjonuje tylko w relacji z Eventem.

2023-01-20 12:49 UTC, RyszardEnv requested changes

2023-01-20 12:49 UTC, RyszardEnv commented on src/main/java/pl/envelo/moovelo/entity/events/EventInfo.java
> +    @OneToOne
Dokładnie tak powinno być.

2023-01-20 12:49 UTC, RyszardEnv commented on src/main/java/pl/envelo/moovelo/entity/Attachment.java
> +
W bazie danych powinniśmy zapisywać ścieżkę do pliku, a nie plik. Plików nie przetrzymuje się w bazie. Tzn. są takie rozwiązania, ale w naszym przypadku skupiłbym się na ścieżce.

2023-01-20 14:30 UTC, mstebel approved these changes

2023-01-20 14:31 UTC, RyszardEnv approved these changes

2023-01-20 14:31 UTC, merged