Be161
akademia-envelo-3/moovelo-back pull request #182
Opened 2023-01-25 14:08 UTC by jkryst

Added actor Mapper Classes with tests, edited VisitorDto

2023-01-25 14:42 UTC, mstebel requested changes

2023-01-25 14:42 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/dto/actor/VisitorDto.java
> -    private long id;
Pole id w VisitorDto jest potrzebne, dziś zostały wprowadzone zmiany w EventParticipationStatsDto i tam wypluwamy Visitora wraz z id

2023-01-25 14:42 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/mapper/actor/VisitorMapper.java
> +                .builder()
zgodnie z poprzednim komentarzem, tutaj id potrzebne będzie

2023-01-25 15:21 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/dto/actor/VisitorDto.java
> -    private long id;
@mstebel id dodane

2023-01-25 15:38 UTC, mstebel approved these changes

2023-01-26 09:50 UTC, Norshyee approved these changes

2023-01-26 09:58 UTC, merged

2023-01-26 10:01 UTC, Przemyslaw-Mazurek approved these changes