Feat: Add getLocation endpoint
akademia-envelo-3/moovelo-back pull request #189
Opened 2023-01-30 12:43 UTC by Przemyslaw-Mazurek

dodanie endpointu które zwraca wspólrzedne geograficzne na podstawie przekazanego adresu

2023-01-30 12:46 UTC, LukaszPietrzykowski16 commented on src/main/java/pl/envelo/moovelo/controller/LocationController.java
> +import org.springframework.beans.factory.annotation.Autowired;
czemu 2 i 3 linijka jest pusta?

2023-01-31 12:25 UTC, Norshyee requested changes

2023-01-31 12:25 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/controller/LocationController.java
> +    }
Nie potrzebny endpoint

2023-01-31 12:25 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/controller/LocationController.java
> +    }
Również tego nie potrzebujemy, jedynie metody w serwisie LocationService

2023-01-31 12:25 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/service/LocationService.java
> +    }
Nazwa nie adekwatna do wykonywanej funkcjonalności, dana metoda wykorzystuje geocodingApi do uzyskania współrzędnych geograficznych na podstawie przekazanego adresu. Natomiast nazwa sugeruje ze pobiera encje location z bazy danych na podstawie przekazanego addressu. Metoda na pewno warta do wykorzystania podczas tworzenia lub edycji Eventu.

2023-02-07 08:46 UTC, closed without merging