BE081 and BE080
akademia-envelo-3/moovelo-back pull request #191
Opened 2023-01-31 11:43 UTC by Norshyee

- https://github.com/akademia-envelo-3/moovelo-back/issues/130
- https://github.com/akademia-envelo-3/moovelo-back/issues/131

2023-01-31 14:02 UTC, mstebel requested changes, later dismissed

2023-01-31 14:02 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/service/actors/EventOwnerService.java
> +    public void checkIfEventOwnerContainsEvents(EventOwner eventOwner) {
tutaj się zdublowalśmy. Ja potrzebuję podobnej metody ale o trochę innej sygnaturze i wygląda to u mnie tak:

 public void removeEventOwnerWithNoEvents(Long userId) {
        log.info("EventOwnerService - removeEventOwnerWithNoEvents()");
        EventOwner eventOwnerByUserId = getEventOwnerByUserId(userId);
        if (eventOwnerByUserId.getEvents().isEmpty()) {
            eventOwnerRepository.delete(eventOwnerByUserId);
            log.info("EventOwnerService - removeEventOwnerWithNoEvents() - eventOwner removed");
        }
    }

Jest opcja, żebyśmy to ujednolcili? Chyba mogę zmienić tak, żeby parametrem był EventOwner ale zostawiłabym nazwę metody remove...(), bo nie tylko sprawdzamy, ale też usuwamy

2023-01-31 14:02 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/event/EventService.java
> +            locationService.checkIfLocationContainsEvents(location);
tutaj też bym zmieniła nazwę na np. removeLocationWithNoEvents()

2023-01-31 14:02 UTC, jkryst requested changes, later dismissed

2023-01-31 14:02 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/entity/events/Event.java
> +    @OneToMany(cascade = CascadeType.ALL)
Czy takie ustawienie w przypadku BasicUserów nie spowoduje ich usunięcia razem z Eventem? W przypadku BasicUserow cascade chyba w ogóle nie jest potrzebne

2023-01-31 14:02 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/entity/events/EventInfo.java
> +    @ManyToOne(cascade = CascadeType.DETACH)
To samo co wyżej. Location chyba miało mieć możliwość użycia ponownie?

2023-01-31 14:02 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/entity/events/InternalEvent.java
> +    @ManyToOne(cascade = CascadeType.ALL)
To samo co wyżej

2023-01-31 14:02 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/entity/surveys/EventSurvey.java
> +    @OneToMany(cascade = CascadeType.ALL)
To samo co wyżej

2023-01-31 14:02 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/service/event/EventService.java
> +            eventOwnerService.checkIfEventOwnerContainsEvents(eventOwner);
Czy taki sam mechanizm nie powinien zostać zastosowany także do hashtagów? Powinniśmy usuwać tylko te, które po usunięciu eventu będą miały pustą listę eventów. To nie jest z tego pr ale CascadeType z List<Hashtag> w evencie też będzie do usunięcia

2023-02-08 14:29 UTC, RyszardEnv approved these changes

2023-02-08 14:30 UTC, Przemyslaw-Mazurek approved these changes

2023-02-08 14:31 UTC, merged