BE082_BE083
akademia-envelo-3/moovelo-back pull request #200
Opened 2023-02-06 12:31 UTC by jkryst

2023-02-07 16:06 UTC, mstebel requested changes

2023-02-07 16:06 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +    public ResponseEntity<List<BasicUserDto>> getUsersWithAccess(@PathVariable Long eventId) {
Może warto tutaj wprowadzić Paging? BasicUserów, którzy mają dostęp do wydarzeń firmowych nieprywatnych będzie dużo

2023-02-07 16:06 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/event/InternalEventService.java
> +    public InternalEvent getInternalEventById(Long id) {
Ta metoda chyba nie jest nigdzie na tą chwilę wykorzystywana

2023-02-13 11:04 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +    public ResponseEntity<List<BasicUserDto>> getUsersWithAccess(@PathVariable Long eventId) {
@mstebel paging dodany

2023-02-13 11:05 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/service/event/InternalEventService.java
> +    public InternalEvent getInternalEventById(Long id) {
@mstebel metoda usunięta

2023-02-13 13:26 UTC, mstebel approved these changes

2023-02-14 08:55 UTC, RyszardEnv approved these changes

2023-02-14 09:54 UTC, merged