BE166
akademia-envelo-3/moovelo-back pull request #210
Opened 2023-02-10 10:43 UTC by jkryst

2023-02-13 09:42 UTC, mstebel reviewed
Fajne to!

2023-02-13 09:42 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/searchspecification/EventSearchSpecification.java
> +            if (Objects.nonNull(privacy)) {
tutaj można by wydzielić kod do osobnych metod prywatnych

2023-02-13 09:42 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/searchspecification/EventSearchSpecification.java
> +        if (sort == null || !sortingParameters.contains(sort)) {
tutaj można by wydzielić kod do osobnych metod prywatnych

2023-02-13 14:21 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/searchspecification/EventSearchSpecification.java
> +            if (Objects.nonNull(privacy)) {
@mstebel osobne metody wydzielone

2023-02-13 14:21 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/searchspecification/EventSearchSpecification.java
> +        if (sort == null || !sortingParameters.contains(sort)) {
@mstebel osobne metody wydzielone

2023-02-14 09:29 UTC, RyszardEnv requested changes

2023-02-14 09:29 UTC, RyszardEnv commented on src/main/java/pl/envelo/moovelo/service/event/EventService.java
> +
Tutaj dałbym parsowanie na bool
boolean eventIsPrivate = Boolean.parseBoolean(privacy);

i do getEventsSpecification() przkazać wartość bool

2023-02-14 09:29 UTC, RyszardEnv commented on src/main/java/pl/envelo/moovelo/controller/searchspecification/EventSearchSpecification.java
> +
połączyć te dwie matody w jedną:

` private static void predicateByPrivacy(boolean eventIsPrivate, Root<Event> root, CriteriaBuilder criteriaBuilder, List<Predicate> predicates) {
        if (isPrivate) {
            predicates.add(criteriaBuilder.isTrue(root.get("isPrivate")));
        } else {
            predicates.add(criteriaBuilder.isFalse(root.get("isPrivate")));
        }
    }`

2023-02-14 09:29 UTC, RyszardEnv commented on src/main/java/pl/envelo/moovelo/controller/searchspecification/EventSearchSpecification.java
> +            predicatePrivacyIsFalse(privacy, root, criteriaBuilder, predicates);
Wywolac tylko jedna metode
predicateByPrivacy();

2023-02-14 12:05 UTC, jkryst commented
@RyszardEnv zrobiłem ten refactor, z tym że privacy musi pozostać Stringiem. Parsowanie na boolean tu nie zadziała, bo zarówno nulle jak i wszelkie złe parametry parsuje na false, a parametr false jest opcjonalny i nie może być automatycznie ustalany przy braku parametru true

2023-02-14 12:12 UTC, Norshyee approved these changes

2023-02-14 12:34 UTC, mstebel approved these changes

2023-02-14 13:30 UTC, RyszardEnv approved these changes

2023-02-14 13:31 UTC, RyszardEnv approved these changes

2023-02-14 13:33 UTC, merged