BE107/BE108
akademia-envelo-3/moovelo-back pull request #211
Opened 2023-02-10 15:10 UTC by Przemyslaw-Mazurek

Dodanie metod addCommentToEvent() i getAllComments() w EventController oraz dodanie CommentMappera.

2023-02-13 10:38 UTC, mstebel requested changes

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/dto/CommentDto.java
>  public class CommentDto {
Ta klasa jest w tym momencie zbędna, jeśli jest CommentResponseDto i CommentRequestDto

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/dto/CommentRequestDto.java
> +public class CommentRequestDto {
Brakuje pola List<Attachement> attachements

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/dto/CommentResponseDto.java
> +    private Long id;
Struktura json do pobrania komentarza poniżej. W klasie CommentResponseDto brakuje pola UserDto; event jest zbędnym polem. Nazwy zmiennych powinny się zgadzać z json  - czyli localDateTime powinno się nazywać `date`. Brakuje pola attachements

{
      "id": 1,
      "user": {
        "firstname": "",
        "lastName": ""
      },
      "date": "",
      "text": "",
      "attachments": [
        {}
        ]
    }

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/dto/EventDto.java
> +public class EventDto {
Ta klasa jest pusta? Czy ona jest potrzebna?

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/event/EventService.java
> +    public List<Comment> getAllComments(Event event){
Korzystasz z pageable, ale zwracasz listę komentarzy, nie stronę. Czy nie powinienieś zwracać Page<Comment>?

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +    public ResponseEntity<List<CommentDto>> getAllComments(@PathVariable Long eventId){
Czy nie powinniśmy zwracać obiektu Page<CommentDto>?

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +        comment.setDate(LocalDateTime.now());
Ta logika powinna być w CommentService

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +        List<CommentDto> commentDtoList = comments.stream()
mapper powinien dotyczyć CommentResponseDto

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/repository/actors/UserRepository.java
> +
puste linie, do usuinięcia

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/CommentService.java
> +    public Comment addComment(Comment comment) {
ta metoda powinna w sobie zawierać utworzenie komentarza - na tą chwilę tworzenie komentarza jest w EventController, a najlepiej by było, jakby było tutaj

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/actors/BasicUserService.java
> +
puste linie

2023-02-13 10:38 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/event/EventService.java
> +
puste linie

2023-02-14 09:14 UTC, Norshyee requested changes

2023-02-14 09:14 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/controller/dto/CommentRequestDto.java
> +public class CommentRequestDto {
List attachmentów powinna być jako List AttachmentDto

2023-02-14 09:14 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/controller/dto/CommentResponseDto.java
> +    private Long id;
zmień nazwę id na commentId, bo jest trochę myląca

2023-02-14 09:14 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +    private BasicUserService basicUserService;
Sprawdź checkstylem zmiany które wprowadziłeś i popraw błędy.

2023-02-14 09:14 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +        return ResponseEntity.ok(commentResponseDtoPage);
Dodaj log co zwraca metoda (ułatwi później debugowanie i poprawę błędów)

2023-02-14 09:14 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/service/CommentService.java
> +
Czy utworzony komentarz nie powinien zostać zapisany do Bazy danych? Chodzi mi o wykorzystanie metody save w CommentRepository

2023-02-14 09:14 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/service/CommentService.java
> +    public Comment addComment(Long eventID, CommentRequestDto commentRequestDto) {
brak logów

2023-02-14 09:14 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/service/actors/BasicUserService.java
> +    public BasicUser getBasicUserById(Long id){
brak logów

2023-02-14 09:14 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/service/event/EventService.java
checkstyle

2023-02-14 09:14 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/service/event/EventService.java
> +    public Page<Comment> getComments (Event event, CommentPage commentPage){
Co dokładnie ta metoda ma robić? Bo na tą chwilę pobiera wszystkie Komentarze z DB i zwraca z paginacją. Parametr event nie jest do niczego wykorzystany (oprócz logów). Czy nie miała pobierać komentarzy dla danego eventu?

2023-02-14 10:54 UTC, mstebel requested changes

2023-02-14 10:54 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/CommentService.java
> +
Do serwisu powinniśmy przekazać już encję przemapowaną z dto, nie dto

2023-02-20 09:32 UTC, mstebel requested changes

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
Admin powinien mieć dostęp do wyświetlania komentarzy

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +        Event event = eventService.getEventById(eventId);
potrzebne jest sprawdzenie, czy zalogowany użytkownik ma dostęp do konkretnego wydarzenie: 
pobranie zalogowanego użytkownika przez AuthorizationService + przez EventService sprawdzenie, czy zalogowany użytkownik jest w liście usersWithAccess danego eventu

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +    public ResponseEntity<?> addComment(@PathVariable Long eventId, @RequestBody @Valid CommentRequestDto commentRequestDto) {
W tej metodzie trzeba sprawdzić, czy zalogowany użytkownik ma dostęp do danego wydarzenia, lub jest właścicielem wydarzenia - sprawdzenie, czy jest właścicielem przez AuthorizationService

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/mapper/AttachmentMapper.java
> +public class AttachmentMapper {
w maperze unikałabym zależności do serwisów - metody mapujące powinny mapować pojedyncze obiekty, a nie listy i dane powinny być pobierane z obiektów przekazanych jako parametry do metody

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/mapper/AttachmentMapper.java
> +    public static List<AttachmentDto> mapFromAttachmentListToAttachmentDtoList(List<Attachment> attachments) {
Odnośnie poprzedniego komentarza, sygnatura metody to : public static AttachmentDto mapAttachmentToAttachmentDto(Attachment attachment) {}

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/mapper/AttachmentMapper.java
> +    public List<Attachment> mapFromAttachmentDtoListToAttachmentList(List<AttachmentDto> attachmentDtoList) {
Zmiana sygnatury metody analogicznie do powyższej

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/mapper/CommentMapper.java
> +                .attachments(comment.getAttachments())
tu powinno być mniej więcej co innego:
.attachments(comment.getAttachments.stream().map(AttachmentMapper::mapAttachmentToAttachmentDto).toList();

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/CommentService.java
> +        Event event = new Event();
tutaj nie powinno być tworzone nowe wydarzenie, tylko pobrane po id z bazy danych. Niepotrzebne jest przypisanie event.setId(1L) na sztywno. Komentarz jest dodawany do istniejącego wydarzenia, nie nowego

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/CommentService.java
> +    public Comment addComment(Long eventID, CommentRequestDto commentRequestDto) {
jako parametr metody public Comment addComment(Long eventID, CommentRequestDto commentRequestDto) nie przekazujesz CommentRequestDto  tylko Comment, który zmapujesz w Contolerze z odebranego obiektu Dto

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/CommentService.java
> +    public Comment addComment(Long eventID, CommentRequestDto commentRequestDto) {
dodatkowo, dobrze by było jako parametr metody przekazać Long userId, żeby nie dodawać w CommentService zależności do AuthenticatedUser & BasicUserService. W kontrolerze możesz odwołać się do AuthorizatinService, pobrać id basicUsera i przekzać go do tej metody

2023-02-20 09:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/event/EventService.java
> +        if (comments.isEmpty()) {
myślę, że nie musimy tutaj rzucać wyjątku - brak komentarzy do wydarzenia, to w sumie nie jest wyjątkowa sytuacja

2023-02-21 15:37 UTC, Norshyee requested changes
Proszę poprawić błędy

2023-02-21 15:37 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/CommentPage.java
> +}
Można stowrzyć ogólną klasę do informacji na temat paginacji

2023-02-21 15:37 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +    private BasicUserService basicUserService;
Szanowny Panie Przemku proszę zostawić tylko commentService a resztę serwisów przenieść do commentService.

Pozdrawiam

2023-02-21 15:37 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +    //TODO Sprawdzić czy user ma dostęp do tego wydarzenia
A co to tu robi?

2023-02-21 15:37 UTC, Norshyee commented on src/main/java/pl/envelo/moovelo/repository/actors/BasicUserRepository.java
> +
a o checkstyle PANIE Przemku to słyszał?

2023-02-22 13:49 UTC, jkryst requested changes

2023-02-22 13:49 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +        }
Po zmergowaniu BE84_BE85 w EventService będzie metoda checkIfUserHasAccessToEvent wykorzystywana kilkukrotnie - dobrze byłoby przenieść to sprawdzanie do serwisu i użyć tej metody

2023-02-22 13:49 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
>          }
tutaj to samo - przenieść do EventService i użyć checkIfUserHasAccessToEvent

2023-02-22 13:49 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/group/GroupInfoService.java
> +package pl.envelo.moovelo.controller.group;
dlaczego klasa serwisowa została przeniesiona do kontrolerów?

2023-02-22 13:49 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/group/GroupService.java
> +package pl.envelo.moovelo.controller.group;
dlaczego klasa serwisowa została przeniesiona do kontrolerów?

2023-02-22 13:49 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/mapper/CommentMapper.java
> +                .attachments(comment.getAttachments())
Lista obiektów Attachment też musi być zmapowana na listę AttachmentDto

2023-02-22 13:49 UTC, jkryst commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +    public ResponseEntity<Page<CommentResponseDto>> getComments(@PathVariable Long eventId, CommentPage commentPage) {
Paginacja nie działa właściwie, pokazuje tylko aktualnie wybraną stronę jako jedyną i pomija obiekty na innych stronach, np. przy 22 elementach i wybraniu strony 0 pokazuje totalPages=1 (powinno być 3), totalElements=10 (powinno być 22)

2023-02-28 10:36 UTC, closed without merging