BE084 BE085
akademia-envelo-3/moovelo-back pull request #231
Opened 2023-02-21 09:05 UTC by jkryst

2023-02-21 13:07 UTC, mdziewiur commented on src/main/java/pl/envelo/moovelo/controller/dto/survey/EventSurveyDto.java
>      private long eventId;
zastanawiam się, czy pole eventId jest potrzebne, w json go nie wykorzystujemy

2023-02-21 13:10 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/service/AuthorizationService.java
> +
właśnie napisałam u siebie identyczną metodę :D

2023-02-21 13:32 UTC, mstebel requested changes

2023-02-21 13:32 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +                }).toList();
Mam propozycję, że pobrać użytkownika w kontrolerze i przekazać go jako parametr do metody -> mapEventSurveyToEventSurveyDto() w EventSurveyMaperze, wtedy możemy pozbyć się logiki z kontrolera

2023-02-22 14:21 UTC, mstebel approved these changes

2023-02-22 14:29 UTC, Przemyslaw-Mazurek approved these changes

2023-02-22 14:32 UTC, merged