BE168
akademia-envelo-3/moovelo-back pull request #235
Opened 2023-02-23 10:54 UTC by Norshyee

2023-02-23 13:12 UTC, RyszardEnv approved these changes

2023-02-23 15:56 UTC, mstebel requested changes
super to wygląda!

2023-02-23 15:56 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +        if (!authorizationService.getLoggedBasicUserId().equals(userId)) {
tutaj chyba można użyć !authorizationService.isLoggedUserIdEqualToBasicUserIdParam(userId);

2023-02-23 15:56 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +        Page<EventListResponseDto> eventAvailableForUserDto = eventMapperManager.mapEventToEventListResponseDto(eventsAvailableForUser, eventMapperInterface);
literówka, events, nie event

2023-02-23 15:56 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/event/EventController.java
> +
brak logu przed wyjściem z metody

2023-02-23 15:56 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/searchspecification/EventSearchSpecification.java
> +        } else if (filterCriteria.isPendingEvents()) {
zmiana `if else` na `if` i wprowadzenie zmian do dokumentacji (endpointy) - filtrowanie po statusie udziału w wydarzeniu

2023-02-23 15:56 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/searchspecification/EventSearchSpecification.java
> +        if (filterCriteria.isGroup()) {
potrzebna zmiana w dokumentacji - opis parametrów filtrowania w endpointach - zmiana z `group` na `isGroup`

2023-02-23 15:56 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/controller/searchspecification/EventSearchSpecification.java
> +        if (filterCriteria.getGroupId() != null) {
może też umieścić w endpointach info o filtrowaniu po groupId i groupName?

2023-02-23 15:56 UTC, mstebel commented on src/main/java/pl/envelo/moovelo/model/SortingAndPagingCriteria.java
> +public class SortingAndPagingCriteria {
defaultowo sortowanie eventów jest po dacie, DESC

2023-02-24 11:58 UTC, mstebel approved these changes

2023-02-24 11:59 UTC, merged