https://github.com/akademia-envelo-3/moovelo-back/issues/12
akademia-envelo-3/moovelo-back pull request #30
Opened 2023-01-12 12:23 UTC by Norshyee

Dotyczy zadania:
 - #12 

Został utworzony pusty projekt spring boot, z dodanym zależnościami opisanymi w tasku.
Zależność spring security, oraz liquibase zostaną wykorzystane w zadaniu #13, po stworzeniu wstępnej dla nich konfiguracji.

2023-01-16 13:09 UTC, mstebel requested changes
do obgadania, czy możemy zostawić tak zależności

2023-01-16 13:09 UTC, mdziewiur commented on pom.xml
> +		</dependency>
zależność oznaczona jako 'provides vulnerable dependency". Może warto zmienić wersję?

2023-01-16 13:09 UTC, mdziewiur commented on pom.xml
> +			<scope>runtime</scope>
zależność oznaczona jako 'provides vulnerable dependency". Może warto zmienić wersję?

2023-01-16 15:29 UTC, Norshyee commented on pom.xml
> +			<scope>runtime</scope>
https://mvnrepository.com/artifact/com.h2database/h2
Każda ma jakieś Vulnerabilities.... :(

2023-01-16 15:34 UTC, Norshyee commented on pom.xml
> +		</dependency>
Najnowsza wersja również posiada 'vulnerable dependency'

2023-01-17 10:50 UTC, jkryst approved these changes

2023-01-18 08:19 UTC, mstebel approved these changes
jest git, bangla!

2023-01-18 08:43 UTC, merged